# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a00c488fbdf23cb0cb621b4a9e936a8757f70102ae022e33ce0ed3a160a0d7ba1e6be69d94790afaeaa8548145a04ecbe33274b4e01d3e41cffe29439c922f

test:
  secret_key_base: 36d0994dfecdfa7e7ca9fc6c51ab7596abe22552b927db87138ae2ce73e5eaea94ada9c9b6b59d287e380d89d6b8a9807089783d0f7372a35bf85a59e948519e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
